### ISSUE TITLE
Nuevo sitio

### ISSUE THREAD

**Issue by ldrojas** [LatamLink/es.latamlink.io#33]
Rediseño completo del sitio de LatamLink

Proceso:
- [ ] Redacción de contenidos #34
- [ ] Mockups del sitio / UX #35
- [ ] Revisión diseño del sitio / UI #36
- [ ] Desarrollo del sitio

Features:
- [ ] Directorio proyectos: #37
